from pathlib import Path
ROOT=Path('.')
EMAIL='mohammedhasgari@gmail.com'
CSS='/assets/conversion-monetization-2026.css'
legal={
'privacy.html':('حریم خصوصی','''<h1>حریم خصوصی</h1><p>این وب‌سایت برای معرفی تخصص، انتشار محتوای فنی و ارائه خدمات فناوری اطلاعات فعالیت می‌کند.</p><h2>داده‌های فنی</h2><p>میزبانی و ابزارهای تحلیلی ممکن است داده‌های فنی مانند IP، مرورگر، دستگاه، زمان و صفحات بازدیدشده را برای امنیت، رفع خطا و تحلیل کلی پردازش کنند.</p><h2>اطلاعات تماس</h2><p>اطلاعاتی که شما داوطلبانه از طریق ایمیل ارسال می‌کنید برای پاسخ‌گویی و پیگیری درخواست استفاده می‌شود.</p><h2>تبلیغات و سرویس‌های شخص ثالث</h2><p>در صورت فعال‌شدن تبلیغات یا ابزارهای شخص ثالث، پردازش داده‌ها تابع سیاست‌های همان سرویس‌ها خواهد بود.</p><p>تماس: <a href="mailto:EMAIL">EMAIL</a></p>'''),
'terms.html':('شرایط استفاده','''<h1>شرایط استفاده</h1><p>محتوای این سایت برای آموزش، مستندسازی فنی و معرفی خدمات شبکه، زیرساخت و امنیت IT منتشر می‌شود.</p><h2>استفاده از مطالب</h2><p>مطالب برای یادگیری و استفاده حرفه‌ای ارائه شده‌اند. بازنشر کامل بدون اجازه مجاز نیست.</p><h2>تغییرات فنی</h2><p>قبل از اعمال تغییر روی سیستم تولید، نسخه پشتیبان، تست و کنترل تغییرات مناسب انجام دهید. مقاله جایگزین ارزیابی اختصاصی محیط شما نیست.</p><h2>خدمات</h2><p>هر پروژه فنی بر اساس محدوده کار، دسترسی، زمان‌بندی، هزینه و مسئولیت‌های توافق‌شده انجام می‌شود.</p>'''),
'disclosure.html':('افشای تبلیغات و همکاری','''<h1>افشای تبلیغات و همکاری</h1><p>این سایت ممکن است در آینده از تبلیغات، Affiliate یا همکاری تجاری استفاده کند. هر همکاری مالی مرتبط با محتوا باید در محل مناسب به‌صورت شفاف اعلام شود.</p><h2>Affiliate</h2><p>ممکن است بعضی لینک‌ها Affiliate باشند و در صورت خرید از آن‌ها کمیسیون ایجاد شود. توصیه‌ها باید بر اساس نیاز واقعی و اطلاعات فنی صفحه بررسی شوند.</p><h2>تبلیغات</h2><p>تبلیغات نباید با محتوای اصلی اشتباه گرفته شوند یا مسیر دسترسی کاربر به اطلاعات را مختل کنند.</p>''')}
def shell(title,body,slug):
 return f'''<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | محمدحسین عسگری ثمرین</title><meta name="description" content="{title} و اطلاعات رسمی وب‌سایت محمدحسین عسگری ثمرین."><meta name="robots" content="index,follow"><meta name="author" content="محمدحسین عسگری ثمرین"><link rel="canonical" href="https://mowhmmdh.github.io/{slug}"><link rel="stylesheet" href="/assets/site-bundle.css"><link rel="stylesheet" href="/assets/site-quality-2026.css"><link rel="stylesheet" href="{CSS}"></head><body><a class="skip-link" href="#main-content">رفتن به محتوای اصلی</a><main id="main-content" class="content" style="max-width:900px;margin:100px auto;padding:24px"><p><a href="/">خانه</a> · <a href="/services.html">خدمات</a> · <a href="/blog/index.html">مقالات</a></p>{body}<hr><p><strong>محمدحسین عسگری ثمرین</strong> · <a href="mailto:{EMAIL}">{EMAIL}</a></p></main></body></html>'''
for slug,(title,body) in legal.items():
 (ROOT/slug).write_text(shell(title,body.replace('EMAIL',EMAIL),slug),encoding='utf-8')
css=ROOT/'assets/conversion-monetization-2026.css'
css.write_text('''.conversion-cta{margin:36px 0;padding:24px;border:1px solid var(--theme-line,#243445);border-radius:20px;background:linear-gradient(135deg,var(--theme-surface2,#12202d),var(--theme-surface,#0d1722));color:var(--theme-text,#f3f6fa)}.conversion-cta p{color:var(--theme-muted,#a5b2c0)}.conversion-cta a{display:inline-block;margin:6px;padding:10px 16px;border-radius:12px;background:var(--theme-accent,#d9ad55);color:#10151b;text-decoration:none;font-weight:700}.legal-footer-2026{max-width:1180px;margin:40px auto 0;padding:24px 20px;border-top:1px solid var(--theme-line,#243445);text-align:center;color:var(--theme-muted,#a5b2c0)}.legal-footer-2026 a{margin:0 6px;color:inherit}''',encoding='utf-8')
cta='''<aside class="conversion-cta" aria-label="درخواست خدمات"><strong>برای یک پروژه واقعی کمک می‌خواهید؟</strong><p>برای بررسی شبکه، زیرساخت، امنیت یا پشتیبانی IT می‌توانید درخواست اولیه خود را ارسال کنید.</p><a href="/services.html">مشاهده خدمات</a><a href="mailto:mohammedhasgari@gmail.com">ارسال درخواست</a></aside>'''
cta_en='''<aside class="conversion-cta" aria-label="Request technical service"><strong>Need help with a real project?</strong><p>Request an initial discussion for network, infrastructure, security or IT support work.</p><a href="/en-services.html">View services</a><a href="mailto:mohammedhasgari@gmail.com">Send request</a></aside>'''
footer='''<footer class="legal-footer-2026"><a href="/privacy.html">حریم خصوصی</a> · <a href="/terms.html">شرایط استفاده</a> · <a href="/disclosure.html">تبلیغات و همکاری</a> · <a href="mailto:mohammedhasgari@gmail.com">تماس</a></footer>'''
for p in ROOT.rglob('*.html'):
 if '.git' in p.parts or '.github' in p.parts or p.name in {'404.html','privacy.html','terms.html','disclosure.html'}: continue
 s=p.read_text(encoding='utf-8',errors='replace')
 if CSS not in s and '</head>' in s: s=s.replace('</head>',f'<link rel="stylesheet" href="{CSS}">\n</head>',1)
 if 'conversion-cta' not in s and ('/blog/' in '/'+p.as_posix() or 'en-blog' in p.parts) and '</main>' in s: s=s.replace('</main>',(cta_en if 'en-blog' in p.parts else cta)+'</main>',1)
 if 'legal-footer-2026' not in s and '</body>' in s: s=s.replace('</body>',footer+'</body>',1)
 p.write_text(s,encoding='utf-8')
print('traffic/conversion/monetization foundation applied')
