from pathlib import Path
import re
from urllib.parse import quote

ROOT = Path('.')
BASE = 'https://mowhmmdh.github.io'
HTMLS = [p for p in ROOT.rglob('*.html') if '.git' not in p.parts]
CSS_RE = re.compile(r'<link\s+[^>]*rel=["\']stylesheet["\'][^>]*href=["\']([^"\']+)["\'][^>]*>', re.I)
CSS_RE2 = re.compile(r'<link\s+[^>]*href=["\']([^"\']+\.css(?:\?[^"\']*)?)["\'][^>]*rel=["\']stylesheet["\'][^>]*>', re.I)
IMG_RE = re.compile(r'<img\b([^>]*?)>', re.I)


def html_url(path: Path) -> str:
    rel = path.as_posix()
    if rel == 'index.html':
        return BASE + '/'
    if rel.endswith('/index.html'):
        return BASE + '/' + rel[:-10]
    return BASE + '/' + rel


def canonical_for(path: Path) -> str:
    # Canonicalize the actual public URL while keeping the existing extension-based routing.
    return html_url(path)


def rewrite_css_urls(css: str, source: Path) -> str:
    def repl(m):
        raw = m.group(1).strip().strip('"\'')
        if not raw or raw.startswith(('data:', 'http://', 'https://', '//', '#', '/')):
            return m.group(0)
        target = (source.parent / raw).resolve()
        try:
            rel = target.relative_to(ROOT.resolve()).as_posix()
            return 'url("/' + quote(rel, safe='/:._-()[]') + '")'
        except ValueError:
            return m.group(0)
    return re.sub(r'url\(\s*([^)]*?)\s*\)', repl, css, flags=re.I)


# 1) Collect every stylesheet actually referenced by HTML, preserving first-seen order.
css_paths = []
seen = set()
for p in HTMLS:
    text = p.read_text(encoding='utf-8')
    refs = CSS_RE.findall(text) + CSS_RE2.findall(text)
    for ref in refs:
        if ref.startswith(('http://', 'https://', '//')):
            continue
        ref_path = ref.split('?', 1)[0].lstrip('/')
        candidate = ROOT / ref_path
        if candidate.exists() and candidate.suffix.lower() == '.css':
            key = candidate.as_posix()
            if key not in seen:
                seen.add(key)
                css_paths.append(candidate)

# Keep the legacy root stylesheet if a page depends on it indirectly; bundle all referenced CSS once.
bundle_parts = [
    '/* Generated by scripts/site-refactor.py. Source order is preserved intentionally. */',
    ':root{color-scheme:light dark}',
]
for css in css_paths:
    content = css.read_text(encoding='utf-8')
    content = rewrite_css_urls(content, css)
    content = content.replace('font-display:swap', 'font-display:optional')
    bundle_parts.append(f'/* --- {css.as_posix()} --- */\n{content}')
(ROOT / 'assets/site-bundle.css').write_text('\n\n'.join(bundle_parts) + '\n', encoding='utf-8')


def ensure_head(text: str, path: Path) -> str:
    lang = 'en' if path.name.startswith('en-') or '/en-blog/' in path.as_posix() or '/en-vintech/' in path.as_posix() or path.name == 'en.html' else 'fa'
    if re.search(r'<html\b[^>]*>', text, re.I):
        text = re.sub(r'<html\b([^>]*)>', lambda m: re.sub(r'\s(?:lang|dir)=["\'][^"\']*["\']', '', m.group(1), flags=re.I) + f' lang="{lang}" dir="{"ltr" if lang=="en" else "rtl"}"', text, count=1, flags=re.I)
    if not re.search(r'<meta\s+name=["\']viewport["\']', text, re.I):
        text = text.replace('<head>', '<head><meta name="viewport" content="width=device-width,initial-scale=1">', 1)
    # Replace the many competing stylesheet requests with exactly one deterministic bundle.
    text = CSS_RE.sub('', text)
    text = CSS_RE2.sub('', text)
    bundle = '<link rel="stylesheet" href="/assets/site-bundle.css">'
    if bundle not in text:
        text = text.replace('</head>', bundle + '</head>', 1)
    # Use the lightweight WebP favicon everywhere.
    text = text.replace('/favicon.png', '/favicon.webp').replace('href="favicon.png"', 'href="favicon.webp"')
    # Images: async decode and lazy-load non-priority images.
    def img_repl(m):
        attrs = m.group(1)
        if 'decoding=' not in attrs:
            attrs += ' decoding="async"'
        if 'loading=' not in attrs and 'fetchpriority="high"' not in attrs:
            attrs += ' loading="lazy"'
        return '<img' + attrs + '>'
    text = IMG_RE.sub(img_repl, text)
    # Canonical: add only if absent, never overwrite a deliberately supplied canonical.
    if not re.search(r'<link\s+rel=["\']canonical["\']', text, re.I):
        text = text.replace('</head>', f'<link rel="canonical" href="{canonical_for(path)}"></head>', 1)
    return text

changed = []
for p in HTMLS:
    old = p.read_text(encoding='utf-8')
    new = ensure_head(old, p)
    if new != old:
        p.write_text(new, encoding='utf-8')
        changed.append(p.as_posix())

print(f'Bundled {len(css_paths)} stylesheets into assets/site-bundle.css')
print(f'Normalized {len(changed)} HTML pages')
for p in changed:
    print(p)
